--- 
title: "Una breve introducción a R con un enfoque financiero y administrativo"
author: "Christian Lochmuller"
date: "2019, actualizado `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Una breve introducción al lenguaje de programación R. Con unos ejemplos del área administrativo y de las finanzas."
---

# Prerequisitos

Los prerequisitos incluyen:

- Conocimientos en términos de los fundamentos de la programación.
- Bajar e installar el lenguaje de programación R ("gratuito"): https://www.r-project.org/
- Bajar e instalar el IDE RStudio Desktop ("gratuito"): https://www.rstudio.com/products/rstudio/download/
- Motivación para aprender sobre la programación con R y capacidad de "aprender a aprender".

También es pertinente señalar, que en la nube esta disponible una versión de R / RStudio: https://rstudio.cloud/. Sin embargo, aquí trabaremos con la versión "desktop".

Según [Wikipedia](https://es.wikipedia.org/wiki/R_%28lenguaje_de_programación%29), "R es un entorno y lenguaje de programación con un enfoque al análisis estadístico". Según esta misma fuente, "R proporciona un amplio abanico de herramientas estadísticas", principalmente en términos de modelos lineales y no lineales, tests estadísticos, análisis de series temporales, algoritmos de clasificación y agrupamiento, etc. R permite también graficar datos en alta calidad.

Los usuarios pueden publicar paquetes que extiendan la funcionalidad básica de R. Para mencionar solo un ejemplo, existen paquetes (librerias), que ofrecen funcionalidad "avanzada", relacionada con las "redes neuronales", ampliando de esta forma la funcionalidad básica disponible. Esto significa, que se puedan desarrollar aplicaciones nuevas basadas en estos paquetes, que faciliten y mejoren estos paquetes de forma libre y continua, literalmente "construyendo sobre los hombros de otros gigantes".

En la actualidad R no solo ofrece funcionalidad con respecto a operaciones estadísticas, sino también con respecto a nuevos desarrollos como p.ej. el aprendizaje de maquina, la inteligencia artifical y el aprendizaje profundo, también con aplicación financiera.

Los paquetes están disponibles, en su gran mayoría, en un repositorio abierto: https://cran.r-project.org/web/packages/, y éstos se pueden bajar libremente a través de la Internet, respetando la licencia de R y RStudio.

¡Bienvenidos a esta breve introducción al lenguaje R con un enfoque y ejemplos financieros y administrativos!

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
